### ISSUE TITLE
Problems with non-ASCII strings

### ISSUE THREAD

**Issue by YtvwlD** [njh/ruby-mqtt#102]
When I run

```
client.get do |topic,message|
    puts message.encoding
```

this, I get `ASCII-8BIT`. And subsequent string uses may fail with non-ASCII strings.

My code works when I do `message = message.force_encoding('utf-8')`. But this is not optimal.

**Comment by njh** [comment]
Hi Niklas,

The payload of a MQTT message is binary (it can't be assumed to be ASCII or UTF-8). Unfortunately Ruby does not have an 'array of bytes' class like other languages do - for example node.js has [Buffer](https://nodejs.org/api/buffer.html). So at the moment, just create a string without specifying a type for it.

I did have a plan to add payload type conversion (see #60) - so maybe passing in `:utf8` as the type could be a solution. Or maybe it is better to assume the buffer is utf8 in the first place is a better default.

nick.

**Comment by YtvwlD** [comment]
Oh, okay. That sounds reasonable. I just assumed that all strings were UTF-8 because of [this comment](https://github.com/njh/ruby-mqtt/blob/38958735278860d5793322c808e6c84694e2aa70/lib/mqtt/packet.rb#L280).

**Comment by njh** [comment]
Ah, yeah. But the payload isn't a string 😨
