### ISSUE TITLE
Offline persistence with clean_session

### ISSUE THREAD

**Issue by csoreff** [njh/ruby-mqtt#109]
If I pass ```clean_session: false``` to client, everything seems to break with ```#0 Protocol error occurs.,MQTT::ProtocolException,Failed to read byte from socket```. Is there a known method for persisting when internet connection is lost? Trying to use a custom fork of https://github.com/toyokazu/fluent-plugin-mqtt-io/tree/remove_reconnection_and_add_qos_retain to allow offline persistence, but having some trouble.

**Comment by njh** [comment]
`clean_session: false` is for server-side persistence. The server should queue-up messages while the client is offline and deliver them when the client re-connects. This should be working fine.

Client-side persistence (i.e. messages trying to be sent while the client is offline) is not currently supported and is covered by #52.
