### ISSUE TITLE
[Discuss] Publishing method return nil. 

### ISSUE THREAD

**Issue by NSLog0** [njh/ruby-mqtt#114]
I'm wondering about the `publish ()` should return response status like a `success`, `error` or there are the other way to get response if it have sorry for that I can't find in the document

**Comment by njh** [comment]
publish() doesn't return anything meaningful but will throw an exception if it fails.

It also doesn't currently wait for PUBACK.

**Comment by avatarr** [comment]
Thank you @njh, Are you still maintain the library? 

Anyway, Do you have an example about best practice of implementation and thread implementation. I've planed to use this on ruby on rail but I need to find some example to determine  `get()` or `get_packet` won't blocks other of application process

**Comment by njh** [comment]
Sorry, I am not sure what you mean in your last comment.

Did you manage to resolve your problem?
