### ISSUE TITLE
Multiple clients

### ISSUE THREAD

**Issue by FranciscoGJ** [njh/ruby-mqtt#116]
I need to connect to two different brokers. How can I do it?

**Comment by njh** [comment]
Just create two different clients.

```ruby
client1 = MQTT::Client.connect('test.mosquitto.org')
client2 = MQTT::Client.connect('iot.eclipse.org')
```

**Comment by FranciscoGJ** [comment]
Yes, I tried. But I can not get the two customers to listen. What would the code be like? Or is it necessary that each instance be found in different threads?

**Comment by njh** [comment]
Can you provide an example of what you are trying to do?

Are you subscribing in both clients?

**Comment by FranciscoGJ** [comment]
This is a example

client1 = MQTT::Client.connect('test.mosquitto.org')
client2 = MQTT::Client.connect('iot.eclipse.org')

client1.get('backend/device/1') do |topic,message|
    @manage.check(topic,message)
end

client2.get('backend/ttn') do |topic,message|
    @manage.check(topic,message)
end

**Comment by DemonGiggle** [comment]
It looks like you are blocked by the first client.get

**Comment by njh** [comment]
That is right. The ruby `MQTT::Client` is synchronous.
The `#get` blocks waiting for a message and calls the block for each message received.

If you want to wait for messages from two different brokers in the same process, then using threads might be an option.
