### ISSUE TITLE
Remove autoload

### ISSUE THREAD

**Issue by njh** [njh/ruby-mqtt#153]
matz says: "I strongly discourage the use of autoload in any standard libraries" (Re: autoload will be dead)
https://bugs.ruby-lang.org/issues/5653

* https://github.com/njh/ruby-mqtt/blob/main/lib/mqtt.rb#L37
* https://github.com/njh/ruby-mqtt/blob/main/lib/mqtt.rb#L38
* https://github.com/njh/ruby-mqtt/blob/main/lib/mqtt.rb#L39

**Comment by njh** [comment]
Oops, I missed this at the end:

> OK, I withdraw the proposal. The autoload method will stay (for Ruby3.0).
> 
> Matz.

Do we keep it or remove it 🤔

**Comment by dentarg** [comment]
If it is working, keep it. 

Pretty sure `autoload` is not going seeing [Zeitwerk](https://github.com/fxn/zeitwerk) exists and is very useful. Projects like [rack](https://github.com/search?q=repo%3Arack%2Frack%20autoload&type=code), [sinatra](https://github.com/search?q=repo%3Asinatra%2Fsinatra%20autoload&type=code), [mail](https://github.com/mikel/mail/blob/2.8.1/lib/mail.rb#L25) and probably many more is using `autoload`.

[With Ruby 3.2.0](https://github.com/ruby/ruby/blob/v3_2_0/NEWS.md#implementation-improvements), this bug https://bugs.ruby-lang.org/issues/18782 `Race conditions in autoload when loading the same feature with multiple threads` was [fixed](https://github.com/ruby/ruby/pull/5898).

**Comment by njh** [comment]
Ok, great. Thank you!
