### ISSUE TITLE
failed to read byte from socket MQTT::ProtocolException

### ISSUE THREAD

**Issue by rolandjitsu** [njh/ruby-mqtt#43]
I keep getting the following issue when I try to run the example code:

``` plain
/Users/rolandjitsu/Projects/Pulsr/Client/vendor/bundle/gems/mqtt-0.2.0/lib/mqtt/packet.rb:271:in `read_byte': Failed to read byte from socket (MQTT::ProtocolException)
from /Users/rolandjitsu/Projects/Pulsr/Client/vendor/bundle/gems/mqtt-0.2.0/lib/mqtt/packet.rb:32:in `read'
from /Users/rolandjitsu/Projects/Pulsr/Client/vendor/bundle/gems/mqtt-0.2.0/lib/mqtt/client.rb:440:in `receive_packet'
from /Users/rolandjitsu/Projects/Pulsr/Client/vendor/bundle/gems/mqtt-0.2.0/lib/mqtt/client.rb:272:in `block in connect'
```

I can successfully subscribe and publish with the [MQTTKit](https://github.com/mobile-web-messaging/MQTTKit) Objective-C implementation of the mosquito lib. But when I run the ruby code, I can see on my device that it's actually trying to publish something (instead of subscribing) and it fails afterwards.

All I am doing is:

``` ruby
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __FILE__)
ENV['RACK_ENV'] ||= 'development'

require 'bundler/setup' if File.exist?(ENV['BUNDLE_GEMFILE'])
Bundler.require :default, ENV['RACK_ENV'].to_sym


# Subscribe example
MQTT::Client.connect(:remote_host => 'iot.eclipse.org', :client_id => 'FBF68BA8') do |client|

    client.get('/pulsr') do |topic, message|
        puts "#{topic}: #{message}"
    end

end
```

**Comment by arjayx** [comment]
hi please, you help me
I have same problem with a mqtt client but not  happen with amqp client, I use a broker rabbitmq, this can to work with two protocols.
More information:
mqtt  => port : 1883
amqp => port 5672
thanks.. :+1:

**Comment by arjayx** [comment]
The code mqtt client :

require "mqtt"

c = MQTT::Client.connect(
  host: '192.168.1.5', 
  port: 1883,
  username: "guest",
  password: "guest")

loop do
  m = "Message mqtt sended @ #{Time.now.to_i} " 
  c.publish("builds", m)
  puts "=> Published #{m}"
  sleep 0.2
end

**Comment by njh** [comment]
This issue is closed, please open a new one.
I will also need more information and example code if I am to help you.
