### ISSUE TITLE
Dynamic Proxying of MQTT based on client auth.

### ISSUE THREAD

**Issue by nzfarmer1** [njh/ruby-mqtt#65]
Here is a challenge that's been troubling me for sometime.

Let's say we have multiple mqtt clients and multiple mqtt backends BUT only one public facing server/port.

We want to identify a user via say their client's SSL Cert or username/password, then proxy all requests for that Client Id (source port/address) to a specific broker based on a lookup table.

Would we be able to configure your tool to support this requirement?

Thank you.

**Comment by njh** [comment]
Hello,

It isn't far off but the following limitations probably make it worth looking at something else:
* The proxy class doesn't support SSL
* The proxy is only currently able to talk to a single backend
* The ruby implementation won't be that performant compared to other implementations

Node.js might be a better choice for this type of thing.

nick.

**Comment by nzfarmer1** [comment]
Thanks nick

You inspired me to roll this today: https://github.com/nzfarmer1/mqtt-proxy

andrew

**Comment by njh** [comment]
Great!
