### ISSUE TITLE
Sample in README.MD is wrong

### ISSUE THREAD

**Issue by jhiemer** [njh/ruby-mqtt#68]
Hi, 
I think the sample in the README.MD should be:

````ruby
MQTT::Client.connect(endpoint) do |c|
  c.publish('test', 'message')
end
````

Instead of 'topic'.

**Comment by jhiemer** [comment]
Pull request created: https://github.com/njh/ruby-mqtt/pull/69

**Comment by njh** [comment]
Thanks!
