### ISSUE TITLE
setting qos to 1 always sending the message

### ISSUE THREAD

**Issue by tindaio** [njh/ruby-mqtt#70]
I test a sample code and set QOS to 1. Why is the server is always sending the message to the subscribe client even the subscribe client already received the message and as I search https://github.com/njh/ruby-mqtt/pull/58 this should solve the problem because in MQTT specs the subscribe client should send PUBACK after receiving the message to tag that message is received. Did I missed something? Any tips?

*sub.rb*

```
require 'rubygems'
require 'mqtt'

MQTT::Client.connect('192.168.9.105') do |client|
  client.get_packet('test'=>1) do |packet|
    puts packet.inspect
  end
end
```

*pub.rb*

```
require 'rubygems'
require 'mqtt'

# Publish example
MQTT::Client.connect('192.168.9.105') do |c|
  c.publish('test', 'message 3', 0, 1)
end
```

**Comment by anarchocurious** [comment]
I am also having this issue. 

@tindaio Were you ever able to solve the problem?

**Comment by tindaio** [comment]
@anarchocurious no solution yet. Using plain http get/post and json solution.

**Comment by anarchocurious** [comment]
@tindaio This issue has already been fixed on master.

Changing my Gemfile entry to ```gem 'mqtt', github: 'njh/ruby-mqtt'``` solves the problem for me.
