### ISSUE TITLE
Please publish a new release to Rubygems

### ISSUE THREAD

**Issue by gevans** [njh/ruby-mqtt#74]
It looks like there hasn't been a release since October 2014. It might be time to push v0.4.0. :smile:

**Comment by njh** [comment]
Hi,

I am not currently happy with the quality/stability of the QoS 1 implementation, which is why I have been delaying making a release.

But maybe I should just get on and release it; then let people submit fixes/improvements.

nick.

**Comment by gevans** [comment]
In that case, a prerelease might be more suitable (e.g. `0.4.0.beta`). Otherwise it's looking like a lot of users are stuck with using a Git clone:

```ruby
gem 'mqtt', github: 'njh/ruby-mqtt'
```

**Comment by njh** [comment]
Sorry, I have been meaning to spend some time on ruby-mqtt and try and resolve the issues I see with QoS 1.

I have got distracted with other projects, so will release 0.4.0-beta today.

**Comment by njh** [comment]
Version [0.4.0](https://github.com/njh/ruby-mqtt/tree/v0.4.0) has been released:
https://rubygems.org/gems/mqtt/versions/0.4.0

Fingers crossed it works well for everyone!
