### ISSUE TITLE
How to connect virtual hosts

### ISSUE THREAD

**Issue by wzdot** [njh/ruby-mqtt#99]
Hi! How to connect mq with virtual hosts, I sorry that I can not find the argument in the Client.rb file

MQTT::Client.connect(host: '127.0.0.1', username: 'admin', password: 'admin', vhost: 'common')

is not work!!!

**Comment by njh** [comment]
Virtual Hosts are not supported in MQTT v3.1.1 - the only official standard for MQTT.

I think they may be added in MQTT v5.

**Comment by wzdot** [comment]
ok, Thanks @njh
